package expo.modules.accessibility

// FIX_C1_TOUCH_SIGNAL_1 (2026-10-04, user-directed) — TYPE_WINDOW_CONTENT_CHANGED (the original
// RUNDA C-1 proxy) fires even with zero touch: the end-of-call screen updating itself, a new
// message arriving. That made the cleanup window skip almost every time. Replaced with
// TYPE_VIEW_CLICKED / TYPE_VIEW_SCROLLED / TYPE_VIEW_TEXT_CHANGED, excluding events generated by
// BENSON's own actions (a 1 s window after each of its own clicks/scrolls/text-sets) — see
// BensonAccessibilityService.lastSelfActionAt. Pure, zero Context dependency, JUnit-tested.
object TouchInteractionClassifier {
  private val TRACKED_TYPES = setOf("click", "scroll", "text_changed")

  fun isUserInteraction(eventType: String, eventTimestampMs: Long, lastSelfActionAtMs: Long, selfActionWindowMs: Long = 1000L): Boolean {
    if (eventType !in TRACKED_TYPES) return false
    return eventTimestampMs - lastSelfActionAtMs >= selfActionWindowMs
  }
}
