const { withAppBuildGradle } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// TASK 5 (product-owner-directed 2026-08-01) — android/ is gitignored and fully regenerated by
// `expo prebuild --clean`, so signingConfigs.release edited by hand in android/app/build.gradle
// disappears on the next clean prebuild. This plugin re-injects it every time, reading the actual
// secrets from release-signing.json at the PROJECT ROOT (gitignored, but outside /android — so it
// survives prebuild) which itself only points at the keystore file; the keystore is kept entirely
// outside the project (see SESSION_REPORT.md for its path) and is never copied into the repo.
//
// If release-signing.json is absent (e.g. a fresh clone without it), this is a silent no-op: the
// release build type keeps Expo's default debug-signing fallback rather than failing the build.

const TAG = '@benson-release-signing';

function loadSigningConfig(projectRoot) {
  const configPath = path.join(projectRoot, 'release-signing.json');
  if (!fs.existsSync(configPath)) return null;
  try {
    const raw = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    if (!raw.storeFile || !raw.storePassword || !raw.keyAlias || !raw.keyPassword) {
      console.warn('[withReleaseSigning] release-signing.json is missing one of storeFile/storePassword/keyAlias/keyPassword — skipping.');
      return null;
    }
    if (!fs.existsSync(raw.storeFile)) {
      console.warn(`[withReleaseSigning] keystore not found at ${raw.storeFile} — skipping, release build will fall back to debug signing.`);
      return null;
    }
    return raw;
  } catch (e) {
    console.warn(`[withReleaseSigning] failed to parse release-signing.json: ${e.message}`);
    return null;
  }
}

function findMatchingBrace(content, openIndex) {
  let depth = 0;
  for (let i = openIndex; i < content.length; i++) {
    if (content[i] === '{') depth++;
    else if (content[i] === '}') {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

function injectSigningConfigsRelease(contents, cfg) {
  if (contents.includes(TAG)) return contents; // already injected — idempotent across re-prebuilds
  const scIdx = contents.indexOf('signingConfigs {');
  if (scIdx === -1) {
    console.warn('[withReleaseSigning] could not find "signingConfigs {" in build.gradle — skipping.');
    return contents;
  }
  const scOpen = contents.indexOf('{', scIdx);
  const scClose = findMatchingBrace(contents, scOpen);
  if (scClose === -1) return contents;
  const storeFileEscaped = cfg.storeFile.replace(/\\/g, '\\\\');
  const releaseBlock = `
        // ${TAG} — injected by plugins/withReleaseSigning.js; keystore lives OUTSIDE this project
        release {
            storeFile file('${storeFileEscaped}')
            storePassword '${cfg.storePassword}'
            keyAlias '${cfg.keyAlias}'
            keyPassword '${cfg.keyPassword}'
        }
`;
  return contents.slice(0, scClose) + releaseBlock + contents.slice(scClose);
}

function injectBuildTypesOverride(contents) {
  const overrideTag = `${TAG}-buildtype`;
  if (contents.includes(overrideTag)) return contents;
  const btIdx = contents.indexOf('buildTypes {');
  if (btIdx === -1) {
    console.warn('[withReleaseSigning] could not find "buildTypes {" in build.gradle — skipping.');
    return contents;
  }
  const btOpen = contents.indexOf('{', btIdx);
  const btClose = findMatchingBrace(contents, btOpen);
  if (btClose === -1) return contents;
  const buildTypesSlice = contents.slice(btOpen, btClose);
  const relIdx = buildTypesSlice.indexOf('release {');
  if (relIdx === -1) {
    console.warn('[withReleaseSigning] could not find buildTypes.release block — skipping.');
    return contents;
  }
  const relOpenBrace = contents.indexOf('{', btOpen + relIdx);
  const relCloseBrace = findMatchingBrace(contents, relOpenBrace);
  if (relCloseBrace === -1) return contents;
  // In Groovy, each `signingConfig X` line is just a setter call — the LAST one executed wins.
  // Inserting immediately before this block's closing brace guarantees ours runs after the
  // template's own default "signingConfig signingConfigs.debug" line, so ours is the one that
  // actually takes effect, without needing to locate/delete that default line.
  const override = `\n            signingConfig signingConfigs.release // ${overrideTag}\n        `;
  return contents.slice(0, relCloseBrace) + override + contents.slice(relCloseBrace);
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    const cfg = loadSigningConfig(config._internal.projectRoot);
    if (!cfg) {
      console.warn('[withReleaseSigning] release-signing.json not found/invalid — release build type keeps default (debug) signing. See SESSION_REPORT.md.');
      return config;
    }
    let contents = config.modResults.contents;
    contents = injectSigningConfigsRelease(contents, cfg);
    contents = injectBuildTypesOverride(contents);
    config.modResults.contents = contents;
    return config;
  });
};
